name: dbd-one

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tax_id:
        description: "ถ้าว่างจะอ่านจาก tax_ids.txt"
        required: false
      limit:
        description: "จำนวนต่อรอบ (0=ทั้งหมด)"
        required: false
        default: "40"
      offset:
        description: "ข้ามรายการแรกกี่อัน (ปกติ 0)"
        required: false
        default: "0"
      skip_existing:
        description: "none/sheet/json/both"
        required: false
        default: "sheet"
  schedule:
    - cron: "*/10 * * * *"   # ทุก 10 นาที

concurrency:
  group: dbd-one
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Remove stale chromedriver in PATH
        run: sudo rm -f /usr/bin/chromedriver || true

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run DBD batch → Google Sheets
        env:
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SHEET_ID: ${{ vars.SHEET_ID }}

          INPUT_TAX_ID:  ${{ inputs.tax_id }}
          INPUT_LIMIT:   ${{ inputs.limit }}
          INPUT_OFFSET:  ${{ inputs.offset }}
          INPUT_SKIP:    ${{ inputs.skip_existing }}
        run: |
          set -e
          LIMIT="${INPUT_LIMIT:-40}"
          OFFSET="${INPUT_OFFSET:-0}"
          SKIP="${INPUT_SKIP:-sheet}"

          ARGS=( --list-file tax_ids.txt --limit "$LIMIT" --offset "$OFFSET" --skip-existing "$SKIP" )
          if [ -n "$INPUT_TAX_ID" ]; then
            ARGS+=( --tax-id "$INPUT_TAX_ID" )
          fi

          python dbd_one.py "${ARGS[@]}" | tee result.txt
          echo "## DBD Result (last 200 lines)" >> $GITHUB_STEP_SUMMARY
          tail -n 200 result.txt >> $GITHUB_STEP_SUMMARY

      - name: Commit JSON results to repo
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data || true
          git commit -m "DBD batch $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nothing to commit"
          git pull --rebase origin "${{ github.ref_name }}" || true
          git push origin HEAD:"${{ github.ref_name }}" || echo "push skipped"

      - name: Upload JSONs as artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbd-json
          path: data/*.json
          if-no-files-found: ignore   # ถ้าไม่มีไฟล์ให้ข้าม ไม่ต้อง error
