name: wiki-search

on:
  workflow_dispatch:
    inputs:
      term:
        description: "คำที่ต้องค้นหาในวิกิพีเดีย"
        required: false
        default: "ประเทศไทย"
      lang:
        description: "ภาษา (th หรือ en)"
        required: false
        default: "th"

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run Wikipedia search
        run: |
          python scrape_wiki.py --term "${{ inputs.term }}" --lang "${{ inputs.lang }}"
